import i18next from 'i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

const resources = {
  en: {
    translation: {
      activeMenuButton: 'Active',
      passiveMenuButton: 'Passive',
      upgradesMenuButton: 'Upgrades',
      challengesMenuButton: 'Challenges',
      prestigeMenuButton: 'Prestige',
      cardsMenuButton: 'Cards',
      achievementsMenuButton: 'Achievements',
      statsMenuButton: 'Stats',
      optionsMenuButton: 'Options',
      multiUpgrade1Desc: '+1 Point per Word!',
      multiUpgrade2Desc: '+1 Letter per word!',
      multiUpgrade3Desc: '+25% Points!',
      passiveFirstGenerator: "Generate Passive Points! | Generators: ",
      passiveSecondGenerator: "Generate the First Generator | Generators: ",
      passiveThirdGenerator: "Generate the Second Generator | Generators: ",
      passiveFourthGenerator: "Generate the Third Generator | Generators: ",
      passiveFifthGenerator: "Generate the Fourth Generator | Generators: ",
      passiveSixthGenerator: "Generate the Fifth Generator | Generators: ",
      passiveSeventhGenerator: "Generate the Sixth Generator | Generators: ",
      passiveCurrency1: "Passive Points",
      passiveCurrency2: "1st Generators",
      passiveCurrency3: "2nd Generators",
      passiveCurrency4: "3rd Generators",
      passiveCurrency5: "4th Generators",
      passiveCurrency6: "5th Generators",
      passiveCurrency7: "6th Generators",
      tierCurrency: "Buy the next Tier of Generators!",
      tierCurrencyAddition: "Previous Tier Generators!",
      bought: "Bought",
      cost: "Cost",
      basicUpgradeHeading: 'Basic Upgrades',
      passiveUpgradeHeading: 'Passive Upgrades',
      prestigeUpgradeHeading: 'Prestige Upgrades',
      genericUpgradeTitle: 'Hover an upgrade to see its description!',
      basicUpgrade1Title: 'First Upgrade of them all',
      basicUpgrade1Desc: 'x1.3 Points',
      basicUpgrade2Title: 'Your words value a little bit more, absolutely',
      basicUpgrade2Desc: '+4 Points per Word',
      basicUpgrade3Title: "I'm speed",
      basicUpgrade3Desc: 'Get a letter per minute counter',
      basicUpgrade4Title: 'You found a word passive enhancer!',
      basicUpgrade4Desc: 'Unlock passive income',
      basicUpgrade5Title: '2nd Upgrade of this type',
      basicUpgrade5Desc: 'x1.5 Points',
      basicUpgrade6Title: 'Every goal has its reward',
      basicUpgrade6Desc: 'Every achievement gives a bonus!',
      basicUpgrade7Title: 'Your words value a bit more more, absolutely again',
      basicUpgrade7Desc: '+10 points per word',
      basicUpgrade8Title: 'You found a Scrabble module!',
      basicUpgrade8Desc: 'Every letter gets a value',
      basicUpgrade9Title: 'Gacha. Yes, gacha',
      basicUpgrade9Desc: 'Unlocks Cards!',
      basicUpgrade10Title: '3rd time',
      basicUpgrade10Desc: 'x2 points',
      basicUpgrade11Title: 'You can challenge yourself to be better next time',
      basicUpgrade11Desc: 'Unlock Challenges!',
      basicUpgrade12Title: 'Last Basic Upgrade! Your words value MORE, a bit more',
      basicUpgrade12Desc: '+20 points per word',
      passiveUpgrade1Title: 'You force the enhancer to be enhancerered',
      passiveUpgrade1Desc: 'x1.25 Points',
      passiveUpgrade2Title: "Here's a little bonus for you",
      passiveUpgrade2Desc: '+5 points per Word',
      passiveUpgrade3Title: "I don't know exactly what to upgrade, I'm sorry",
      passiveUpgrade3Desc: 'x1.5 Points',
      passiveUpgrade4Title: 'Wow, it seems that they made a Scrabble module for the enhancer too. Interesting',
      passiveUpgrade4Desc: 'Every letter gets a value',
      passiveUpgrade5Title: 'Horizontal scaling ftw',
      passiveUpgrade5Desc: '+1 Letter',
      passiveUpgrade6Title: 'More modules! This time you found a synergy module.',
      passiveUpgrade6Desc: 'Every Generator Bought gives a Bonus to the other Generators!',
      prestigeUpgrade1Title: 'Welcome to Prestige! Take a free x2 multiplier',
      prestigeUpgrade1Desc: 'Yes',
      prestigeUpgrade2Title: 'The Gacha Gods have spoken',
      prestigeUpgrade2Desc: '+2 Cards Per Roll',
      prestigeUpgrade3Title: 'Better Scaling for MultiUpgrades!',
      prestigeUpgrade3Desc: 'x1.25 Points',
      prestigeUpgrade4Title: 'It seems that the next time you Prestige you can bring the enhancer with you. But the upgrades must wear out',
      prestigeUpgrade4Desc: 'Keep your Passive Income (Not your upgrades) when Prestige! (PP resets too)',
      prestigePointsToGet: 'Prestige Points when Prestige:',
      prestigePointsAmount: 'Prestige Points:',
      prestigeButton: 'Prestige!',
      card1Title: 'Fast+ Progress (C)',
      card2Title: '+1 Points (C)',
      card3Title: '10% Passive Points (C)',
      card4Title: '2 Passive Points (C)',
      card5Title: 'Faster Progress (UC)',
      card6Title: '+3 Points (UC)',
      card7Title: '25% Passive Points (UC)',
      card8Title: '+5 Passive Points (UC)',
      card9Title: 'Faster Passive Words (UC)',
      card10Title: 'Longer Passive Words (UC)',
      card11Title: 'Fasterer Progress (E)',
      card12Title: 'All Lowercase (E)',
      card13Title: '+6 Points (E)',
      card14Title: '50% Passive Points (E)',
      card15Title: '+10 Passive Points (E)',
      card16Title: 'Fasterer Passive Words (E)',
      card17Title: 'Longerer Passive Words (E)',
      card18Title: 'Fastest Progress (L)',
      card19Title: '+10 Points (L)',
      card20Title: 'x2 Passive Points (L)',
      card21Title: '+25 Passive Points (L)',
      card22Title: 'Fastest Passive Words (L)',
      card23Title: 'Longest Passive Words (L)',
    },
  },
  es: {
    translation: {
      activeMenuButton: 'Activo',
      passiveMenuButton: 'Pasivo',
      upgradesMenuButton: 'Mejoras',
      challengesMenuButton: 'Desafíos',
      prestigeMenuButton: 'Prestigio',
      cardsMenuButton: 'Cartas',
      achievementsMenuButton: 'Logros',
      statsMenuButton: 'Estadísticas',
      optionsMenuButton: 'Opciones',
      multiUpgrade1Desc: '+1 Punto por Palabra!',
      multiUpgrade2Desc: '+1 Letra por Palabra!',
      multiUpgrade3Desc: '+25% Puntos!',
      passiveFirstGenerator: "Genera Puntos Pasivos! | Generadores: ",
      passiveSecondGenerator: "Genera el Primer Generador | Generadores: ",
      passiveThirdGenerator: "Genera the Segundo Generador | Generadores: ",
      passiveFourthGenerator: "Genera the Tercer Generador | Generadores: ",
      passiveFifthGenerator: "Genera the Cuarto Generador | Generadores: ",
      passiveSixthGenerator: "Genera the Quinto Generador | Generadores: ",
      passiveSeventhGenerator: "Genera the Sexto Generador | Generadores: ",
      passiveCurrency1: "Puntos Pasivos",
      passiveCurrency2: "1ros Generadores",
      passiveCurrency3: "2dos Generadores",
      passiveCurrency4: "3ros Generadores",
      passiveCurrency5: "4tos Generadores",
      passiveCurrency6: "5tos Generadores",
      passiveCurrency7: "6tos Generadores",
      tierCurrency: "Compra el siguiente nivel de Generadores",
      tierCurrencyAddition: "Generadores del Nivel Anterior!",
      bought: "Comprados",
      cost: "Costo",
      basicUpgradeHeading: 'Mejoras Básicas',
      passiveUpgradeHeading: 'Mejoras Pasivas',
      prestigeUpgradeHeading: 'Mejoras Prestigio',
      genericUpgradeTitle: 'Desplazá tu mouse sobre las mejoras para ver su descripción!',
      basicUpgrade1Title: 'La primera mejora de todas',
      basicUpgrade1Desc: 'x1.3 Puntos',
      basicUpgrade2Title: 'Tus palabras valen un poquito más, absolutamente',
      basicUpgrade2Desc: '+4 Puntos por Palabra',
      basicUpgrade3Title: 'Rápido y Furioso',
      basicUpgrade3Desc: 'Obtienes un contador de Letras por Minuto',
      basicUpgrade4Title: 'Encontraste un mejorador de palabras pasivo!',
      basicUpgrade4Desc: 'Desbloqueas Ganancia Pasiva',
      basicUpgrade5Title: '2nda Mejora de este estilo',
      basicUpgrade5Desc: 'x1.5 Puntos',
      basicUpgrade6Title: 'Cada meta tiene su recompensa',
      basicUpgrade6Desc: 'Cada logro te da un bonus!',
      basicUpgrade7Title: 'Tus palabras valen un poquito más, un poquito más, absolutamente de vuelta',
      basicUpgrade7Desc: '+10 Puntos por Palabra',
      basicUpgrade8Title: 'Encuentras un módulo Scrabble!',
      basicUpgrade8Desc: 'Todas las letras obtienen un valor',
      basicUpgrade9Title: 'Gacha. Sí, gacha',
      basicUpgrade9Desc: 'Desbloqueas las Cartas!',
      basicUpgrade10Title: '3ra vez',
      basicUpgrade10Desc: 'x2 Puntos',
      basicUpgrade11Title: 'Puedes desafiarte a ser un poco mejor la próxima vez',
      basicUpgrade11Desc: 'Desbloqueas los desafíos!',
      basicUpgrade12Title: 'Última mejora básica! Tus palabras valen MÁS, un poco más',
      basicUpgrade12Desc: '+20 Puntos por palabra',
      passiveUpgrade1Title: 'Forzás al mejorador a ser mejoradorado',
      passiveUpgrade1Desc: 'x1.25 Puntos',
      passiveUpgrade2Title: 'Toma este pequeño bonus para vos',
      passiveUpgrade2Desc: '+5 Puntos por Palabra',
      passiveUpgrade3Title: 'No te voy a mentir, no sé que mejorar',
      passiveUpgrade3Desc: 'x1.5 Puntos',
      passiveUpgrade4Title: 'Wow, parece ser que hicieron un módulo Scrabble para el mejorador también. Interesante',
      passiveUpgrade4Desc: 'Cada letra obtiene un valor',
      passiveUpgrade5Title: 'Viva el Escalado horizontal',
      passiveUpgrade5Desc: '+1 letra',
      passiveUpgrade6Title: 'Más módulos! Esta vez encontrás un módulo de Sinergia',
      passiveUpgrade6Desc: 'Cada generador comprado le da un bonus a los otros generadores',
      prestigeUpgrade1Title: 'Bienvenido a Prestigio! Toma un multiplicador de doble de Puntos gratis',
      prestigeUpgrade1Desc: 'Sí',
      prestigeUpgrade2Title: 'Los Dioses del Gacha han hablado',
      prestigeUpgrade2Desc: '+2 Cartas por Tirada',
      prestigeUpgrade3Title: 'Un mejor escalado de coste de las Multimejoras!',
      prestigeUpgrade3Desc: 'Es un secreto!',
      prestigeUpgrade4Title: 'Parece ser que la próxima vez que prestigies te puedes traer el mejorador contigo. Pero las mejoras se pierden.',
      prestigeUpgrade4Desc: 'Mantén tu Ganancia Pasiva (Las mejoras no) cuando prestigias! (PP se resetean)',
      prestigePointsToGet: 'Puntos de Prestigio al realizarlo:',
      prestigePointsAmount: 'Puntos de Prestigio:',
      prestigeButton: 'Prestigia!',
      card1Title: 'Progreso Rápido+ (C)',
      card2Title: '+1 Punto (C)',
      card3Title: '10% Puntos Pasivos (C)',
      card4Title: '2 Puntos Pasivos (C)',
      card5Title: 'Progreso más Rápido (UC)',
      card6Title: '+3 Puntos (UC)',
      card7Title: '25% Puntos Pasivos (UC)',
      card8Title: '+5 Puntos Pasivos (UC)',
      card9Title: 'Palabras Pasivas Más Rápidas (UC)',
      card10Title: 'Palabras Pasivas más Largas (UC)',
      card11Title: 'Progreso un poco más más Rápido (E)',
      card12Title: 'Todo minúsculas (E)',
      card13Title: '+6 Puntos (E)',
      card14Title: '50% Puntos Pasivos (E)',
      card15Title: '+10 Puntos Pasivos (E)',
      card16Title: 'Palabras Pasivas Bastante Más Rápidas (E)',
      card17Title: 'Palabras Pasivas Bastante Más Largas (E)',
      card18Title: 'El Progreso Más Rápido (L)',
      card19Title: '+10 Puntos (L)',
      card20Title: 'x2 Puntos Pasivos (L)',
      card21Title: '+25 Puntos Pasivos (L)',
      card22Title: 'Las Palabras Más Rápidas (L)',
      card23Title: 'Las Palabras Más Largas (L)',
    },
  },
};

i18next
  .use(LanguageDetector)
  .init({
    resources,
    fallbackLng: 'en',
  });

export default i18next;