import i18next from 'i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

const resources = {
  en: {
    translation: {
      save: 'Save',
      log: 'Log',
      activeMenuButton: 'Active',
      passiveMenuButton: 'Passive',
      upgradesMenuButton: 'Upgrades',
      challengesMenuButton: 'Challenges',
      prestigeMenuButton: 'Prestige',
      cardsMenuButton: 'Cards',
      achievementsMenuButton: 'Achievements',
      statsMenuButton: 'Stats',
      optionsMenuButton: 'Options',
      multiUpgrade1Desc: '+1 Point per Word!',
      multiUpgrade2Desc: '+1 Letter per word!',
      multiUpgrade3Desc: '+25% Points!',
      passiveFirstGenerator: "Generate Passive Points! | Generators: ",
      passiveSecondGenerator: "Generate the First Generator | Generators: ",
      passiveThirdGenerator: "Generate the Second Generator | Generators: ",
      passiveFourthGenerator: "Generate the Third Generator | Generators: ",
      passiveFifthGenerator: "Generate the Fourth Generator | Generators: ",
      passiveSixthGenerator: "Generate the Fifth Generator | Generators: ",
      passiveSeventhGenerator: "Generate the Sixth Generator | Generators: ",
      passiveCurrency1: "Passive Points",
      passiveCurrency2: "1st Generators",
      passiveCurrency3: "2nd Generators",
      passiveCurrency4: "3rd Generators",
      passiveCurrency5: "4th Generators",
      passiveCurrency6: "5th Generators",
      passiveCurrency7: "6th Generators",
      tierCurrency: "Buy the next Tier of Generators!",
      tierCurrencyAddition: "Previous Tier Generators!",
      bought: "Bought",
      cost: "Cost",
      basicUpgradeHeading: 'Basic Upgrades',
      passiveUpgradeHeading: 'Passive Upgrades',
      prestigeUpgradeHeading: 'Prestige Upgrades',
      genericUpgradeTitle: 'Hover an upgrade to see its description!',
      basicUpgrade1Title: 'First Upgrade of them all',
      basicUpgrade1Desc: 'x1.3 Points',
      basicUpgrade2Title: 'Your words value a little bit more, absolutely',
      basicUpgrade2Desc: '+4 Points per Word',
      basicUpgrade3Title: "I'm speed",
      basicUpgrade3Desc: 'Get a letter per minute counter',
      basicUpgrade4Title: 'You found a word passive enhancer!',
      basicUpgrade4Desc: 'Unlock passive income',
      basicUpgrade5Title: '2nd Upgrade of this type',
      basicUpgrade5Desc: 'x1.5 Points',
      basicUpgrade6Title: 'Every goal has its reward',
      basicUpgrade6Desc: 'Every achievement gives a bonus!',
      basicUpgrade7Title: 'Your words value a bit more more, absolutely again',
      basicUpgrade7Desc: '+10 points per word',
      basicUpgrade8Title: 'You found a Scrabble module!',
      basicUpgrade8Desc: 'Every letter gets a value',
      basicUpgrade9Title: 'Gacha. Yes, gacha',
      basicUpgrade9Desc: 'Unlocks Cards!',
      basicUpgrade10Title: '3rd time',
      basicUpgrade10Desc: 'x2 points',
      basicUpgrade11Title: 'You can challenge yourself to be better next time',
      basicUpgrade11Desc: 'Unlock Challenges!',
      basicUpgrade12Title: 'Last Basic Upgrade! Your words value MORE, a bit more',
      basicUpgrade12Desc: '+20 points per word',
      passiveUpgrade1Title: 'You force the enhancer to be enhancerered',
      passiveUpgrade1Desc: 'x1.25 Points',
      passiveUpgrade2Title: "Here's a little bonus for you",
      passiveUpgrade2Desc: '+5 points per Word',
      passiveUpgrade3Title: "I don't know exactly what to upgrade, I'm sorry",
      passiveUpgrade3Desc: 'x1.5 Points',
      passiveUpgrade4Title: 'Wow, it seems that they made a Scrabble module for the enhancer too. Interesting',
      passiveUpgrade4Desc: 'Every letter gets a value',
      passiveUpgrade5Title: 'Horizontal scaling ftw',
      passiveUpgrade5Desc: '+1 Letter',
      passiveUpgrade6Title: 'More modules! This time you found a synergy module.',
      passiveUpgrade6Desc: 'Every Generator Bought gives a Bonus to the other Generators!',
      prestigeUpgrade1Title: 'Welcome to Prestige! Take a free x2 multiplier',
      prestigeUpgrade1Desc: 'Yes',
      prestigeUpgrade2Title: 'The Gacha Gods have spoken',
      prestigeUpgrade2Desc: '+2 Cards Per Roll',
      prestigeUpgrade3Title: 'Better Scaling for MultiUpgrades!',
      prestigeUpgrade3Desc: 'x1.25 Points',
      prestigeUpgrade4Title: 'It seems that the next time you Prestige you can bring the enhancer with you. But the upgrades must wear out',
      prestigeUpgrade4Desc: 'Keep your Passive Income (Not your upgrades) when Prestige! (PP resets too)',
      prestigePointsToGet: 'Prestige Points when Prestige:',
      prestigePointsAmount: 'Prestige Points:',
      prestigeButton: 'Prestige!',
      card1Title: 'Fast+ Progress (C)',
      card1Desc: '+5% Points',
      card2Title: '+1 Points (C)',
      card2Desc: '+1 Point Per Word',
      card3Title: '+10% Passive Points (C)',
      card3Desc: '+10% Passive Points!',
      card4Title: '+2 Passive Points (C)',
      card4Desc: '+2 Passive Points Per Word!',
      card5Title: 'Faster Progress (UC)',
      card5Desc: '+25% Points',
      card6Title: '+3 Points (UC)',
      card6Desc: '+3 Points Per Word',
      card7Title: '+25% Passive Points (UC)',
      card7Desc: '+25% Passive Points!',
      card8Title: '+5 Passive Points (UC)',
      card8Desc: '+5 Passive Points Per Word!',
      card9Title: 'Faster Passive Words (UC)',
      card9Desc: 'Generate Passive Words 5% Faster',
      card10Title: 'Longer Passive Words (UC)',
      card10Desc: '+1 Letter Per Passive Word',
      card11Title: 'Fasterer Progress (E)',
      card11Desc: '+50% Points',
      card12Title: 'All Lowercase (E)',
      card12Desc: 'From now on, every word is lowercase',
      card13Title: '+6 Points (E)',
      card13Desc: '+6 Points Per Word',
      card14Title: '+50% Passive Points (E)',
      card14Desc: '50% Passive Points!',
      card15Title: '+10 Passive Points (E)',
      card15Desc: '+10 Passive Points Per Word!',
      card16Title: 'Fasterer Passive Words (E)',
      card16Desc: 'Generate Passive Words 10% Faster',
      card17Title: 'Longerer Passive Words (E)',
      card17Desc: '+2 Letters Per Passive Word',
      card18Title: 'Fastest Progress (L)',
      card18Desc: '+100% Points',
      card19Title: '+10 Points (L)',
      card19Desc: '+10 Points Per Word',
      card20Title: 'x2 Passive Points (L)',
      card20Desc: 'Double Passive Points!',
      card21Title: '+25 Passive Points (L)',
      card21Desc: '+25 Passive Points Per Word!',
      card22Title: 'Fastest Passive Words (L)',
      card22Desc: 'Generate Passive Words 20% Faster',
      card23Title: 'Longest Passive Words (L)',
      card23Desc: '+5 Letters Per Passive Word',
      YouHave: 'You have',
      BonusPoints: 'Bonus Points',
      BonusPassivePoints: 'Bonus Passive Points',
      Faster: 'faster',
      And: 'and',
      LetterLongerPassiveWords: 'letter/s longer Passive Words',
      GetAPack: 'Get a Pack',
      Free: 'Free',
      challenge1Title: 'Accuracy',
      challenge1Desc: 'Write 4-letter Words with only a set amount of key presses',
      challenge1Reward: 'REWARD: +1 Card everytime you roll!',
      challenge2Title: 'Speed',
      challenge2Desc: 'Write 4-letter words in only 1 minute',
      challenge2Reward: 'REWARD: 50% more Points!',
      exitChallenge: 'Exit Challenge',
      Success: 'Success',
      Failed: 'Failed',
      pointsStat: 'Points Amount',
      maxLengthStat: 'Max Length',
      bestWordStat: 'Best Word',
      Points: 'Points',
      multiUpgradesStat: 'Multiupgrades',
      achievementsAmountStat: 'Achievements Amount',
      wordsAmountStat: 'Words Typed',
      passiveLengthStat: 'Passive Word Length',
      passivePointsStat: 'Passive Points',
      cardsAmountStat: 'Cards Amount',
    },
  },
  es: {
    translation: {
      save: 'Guardar',
      log: 'Loguear',
      activeMenuButton: 'Activo',
      passiveMenuButton: 'Pasivo',
      upgradesMenuButton: 'Mejoras',
      challengesMenuButton: 'Desafíos',
      prestigeMenuButton: 'Prestigio',
      cardsMenuButton: 'Cartas',
      achievementsMenuButton: 'Logros',
      statsMenuButton: 'Estadísticas',
      optionsMenuButton: 'Opciones',
      multiUpgrade1Desc: '+1 Punto por Palabra!',
      multiUpgrade2Desc: '+1 Letra por Palabra!',
      multiUpgrade3Desc: '+25% Puntos!',
      passiveFirstGenerator: "Genera Puntos Pasivos! | Generadores: ",
      passiveSecondGenerator: "Genera el Primer Generador | Generadores: ",
      passiveThirdGenerator: "Genera the Segundo Generador | Generadores: ",
      passiveFourthGenerator: "Genera the Tercer Generador | Generadores: ",
      passiveFifthGenerator: "Genera the Cuarto Generador | Generadores: ",
      passiveSixthGenerator: "Genera the Quinto Generador | Generadores: ",
      passiveSeventhGenerator: "Genera the Sexto Generador | Generadores: ",
      passiveCurrency1: "Puntos Pasivos",
      passiveCurrency2: "1ros Generadores",
      passiveCurrency3: "2dos Generadores",
      passiveCurrency4: "3ros Generadores",
      passiveCurrency5: "4tos Generadores",
      passiveCurrency6: "5tos Generadores",
      passiveCurrency7: "6tos Generadores",
      tierCurrency: "Compra el siguiente nivel de Generadores",
      tierCurrencyAddition: "Generadores del Nivel Anterior!",
      bought: "Comprados",
      cost: "Costo",
      basicUpgradeHeading: 'Mejoras Básicas',
      passiveUpgradeHeading: 'Mejoras Pasivas',
      prestigeUpgradeHeading: 'Mejoras Prestigio',
      genericUpgradeTitle: 'Desplazá tu mouse sobre las mejoras para ver su descripción!',
      basicUpgrade1Title: 'La primera mejora de todas',
      basicUpgrade1Desc: 'x1.3 Puntos',
      basicUpgrade2Title: 'Tus palabras valen un poquito más, absolutamente',
      basicUpgrade2Desc: '+4 Puntos por Palabra',
      basicUpgrade3Title: 'Rápido y Furioso',
      basicUpgrade3Desc: 'Obtienes un contador de Letras por Minuto',
      basicUpgrade4Title: 'Encontraste un mejorador de palabras pasivo!',
      basicUpgrade4Desc: 'Desbloqueas Ganancia Pasiva',
      basicUpgrade5Title: '2nda Mejora de este estilo',
      basicUpgrade5Desc: 'x1.5 Puntos',
      basicUpgrade6Title: 'Cada meta tiene su recompensa',
      basicUpgrade6Desc: 'Cada logro te da un bonus!',
      basicUpgrade7Title: 'Tus palabras valen un poquito más, un poquito más, absolutamente de vuelta',
      basicUpgrade7Desc: '+10 Puntos por Palabra',
      basicUpgrade8Title: 'Encuentras un módulo Scrabble!',
      basicUpgrade8Desc: 'Todas las letras obtienen un valor',
      basicUpgrade9Title: 'Gacha. Sí, gacha',
      basicUpgrade9Desc: 'Desbloqueas las Cartas!',
      basicUpgrade10Title: '3ra vez',
      basicUpgrade10Desc: 'x2 Puntos',
      basicUpgrade11Title: 'Puedes desafiarte a ser un poco mejor la próxima vez',
      basicUpgrade11Desc: 'Desbloqueas los desafíos!',
      basicUpgrade12Title: 'Última mejora básica! Tus palabras valen MÁS, un poco más',
      basicUpgrade12Desc: '+20 Puntos por palabra',
      passiveUpgrade1Title: 'Forzás al mejorador a ser mejoradorado',
      passiveUpgrade1Desc: 'x1.25 Puntos',
      passiveUpgrade2Title: 'Toma este pequeño bonus para vos',
      passiveUpgrade2Desc: '+5 Puntos por Palabra',
      passiveUpgrade3Title: 'No te voy a mentir, no sé que mejorar',
      passiveUpgrade3Desc: 'x1.5 Puntos',
      passiveUpgrade4Title: 'Wow, parece ser que hicieron un módulo Scrabble para el mejorador también. Interesante',
      passiveUpgrade4Desc: 'Cada letra obtiene un valor',
      passiveUpgrade5Title: 'Viva el Escalado horizontal',
      passiveUpgrade5Desc: '+1 letra',
      passiveUpgrade6Title: 'Más módulos! Esta vez encontrás un módulo de Sinergia',
      passiveUpgrade6Desc: 'Cada generador comprado le da un bonus a los otros generadores',
      prestigeUpgrade1Title: 'Bienvenido a Prestigio! Toma un multiplicador de doble de Puntos gratis',
      prestigeUpgrade1Desc: 'Sí',
      prestigeUpgrade2Title: 'Los Dioses del Gacha han hablado',
      prestigeUpgrade2Desc: '+2 Cartas por Tirada',
      prestigeUpgrade3Title: 'Un mejor escalado de coste de las Multimejoras!',
      prestigeUpgrade3Desc: 'Es un secreto!',
      prestigeUpgrade4Title: 'Parece ser que la próxima vez que prestigies te puedes traer el mejorador contigo. Pero las mejoras se pierden.',
      prestigeUpgrade4Desc: 'Mantén tu Ganancia Pasiva (Las mejoras no) cuando prestigias! (PP se resetean)',
      prestigePointsToGet: 'Puntos de Prestigio al realizarlo:',
      prestigePointsAmount: 'Puntos de Prestigio:',
      prestigeButton: 'Prestigia!',
      card1Title: 'Progreso Rápido+ (C)',
      card1Desc: '+5% Puntos',
      card2Title: '+1 Punto (C)',
      card2Desc: '+1 Punto Por Palabra',
      card3Title: '+10% Puntos Pasivos (C)',
      card3Desc: '+10% Puntos Pasivos',
      card4Title: '+2 Puntos Pasivos (C)',
      card4Desc: '+2 Puntos Pasivos Por Palabra',
      card5Title: 'Progreso más Rápido (UC)',
      card5Desc: '+25% Puntos',
      card6Title: '+3 Puntos (UC)',
      card6Desc: '+3 Puntos Por Palabra',
      card7Title: '+25% Puntos Pasivos (UC)',
      card7Desc: '+25% Puntos Pasivos!',
      card8Title: '+5 Puntos Pasivos (UC)',
      card8Desc: '+5 Puntos Pasivos Por Palabra!',
      card9Title: 'Palabras Pasivas Más Rápidas (UC)',
      card9Desc: 'Generas Palabras Pasivas un 5% Más Rápido',
      card10Title: 'Palabras Pasivas más Largas (UC)',
      card10Desc: '+1 Letra Por Palabra Pasiva',
      card11Title: 'Progreso un poco más más Rápido (E)',
      card11Desc: '+50% Puntos',
      card12Title: 'Todo minúsculas (E)',
      card12Desc: 'A partir de ahora, todas las palabras estarán en minúscula',
      card13Title: '+6 Puntos (E)',
      card13Desc: '+6 Puntos Por Palabra',
      card14Title: '+50% Puntos Pasivos (E)',
      card14Desc: '+50% Puntos Pasivos!',
      card15Title: '+10 Puntos Pasivos (E)',
      card15Desc: '+10 Puntos Pasivos Por Palabra!',
      card16Title: 'Palabras Pasivas Bastante Más Rápidas (E)',
      card16Desc: 'Generas Palabras Pasivas un 10% Más Rápido',
      card17Title: 'Palabras Pasivas Bastante Más Largas (E)',
      card17Desc: '+2 Letras Por Palabra Pasiva',
      card18Title: 'El Progreso Más Rápido (L)',
      card18Desc: 'x2 Puntos',
      card19Title: '+10 Puntos (L)',
      card19Desc: '+10 Puntos Por Palabra',
      card20Title: 'x2 Puntos Pasivos (L)',
      card20Desc: 'Puntos Pasivos Dobles',
      card21Title: '+25 Puntos Pasivos (L)',
      card21Desc: '+25 Puntos Pasivos Por Palabra!',
      card22Title: 'Las Palabras Más Rápidas (L)',
      card22Desc: 'Genera Palabras Pasivas un 20% Más Rápido',
      card23Title: 'Las Palabras Más Largas (L)',
      card23Desc: '+5 Letras Por Palabra Pasiva',
      YouHave: 'Tienes',
      BonusPoints: 'Puntos Bonus',
      BonusPassivePoints: 'Puntos Pasivos Bonus',
      Faster: 'Más rápido',
      And: 'y',
      LetterLongerPassiveWords: 'letra/s más por Palabra Pasiva',
      GetAPack: 'Obtén un Pack',
      Free: 'Gratis',
      challenge1Title: 'Precisión',
      challenge1Desc: 'Escribe palabras de 4 letras con un número de tecleadas disponibles',
      challenge1Reward: 'RECOMPENSA: +1 Carta por Tirada!',
      challenge2Title: 'Velocidad',
      challenge2Desc: 'Escribe palabras de 4 letras en un minuto',
      challenge2Reward: 'RECOMPENSA: 50% más puntos!',
      exitChallenge: 'Salir del desafío',
      Success: 'Success',
      Failed: 'Failed',
      pointsStat: 'Cantidad de Puntos',
      maxLengthStat: 'Max Cantidad de Letras',
      bestWordStat: 'Mejor Palabra',
      Points: 'Puntos',
      multiUpgradesStat: 'Multimejoras',
      achievementsAmountStat: 'Cantidad de Logros',
      wordsAmountStat: 'Palabras Escritas',
      passiveLengthStat: 'Longitud de Palabra Pasiva',
      passivePointsStat: 'Puntos Pasivos',
      cardsAmountStat: 'Cantidad de Cartas',
    },
  },
};

i18next
  .use(LanguageDetector)
  .init({
    resources,
    fallbackLng: 'en',
  });

export default i18next;